# Generated by Django 5.2.7 on 2025-10-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='exemplo@email.com', max_length=254),
        ),
    ]
