# Generated by Django 5.2.7 on 2025-10-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='produto_favorito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
